In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

In [2]:
data = pd.read_csv('salaries1.csv')

In [3]:
data.head()

company  job  degree  salary_more_then_100k
0        1    0       0                      0
1        1    0       1                      0
2        1    1       0                      1
3        1    1       1                      1
4        1    2       0                      0

In [4]:
X = data.iloc[:,:-1].values

In [5]:
X

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 2, 0],
       [1, 2, 1],
       [0, 0, 1],
       [0, 2, 0],
       [0, 1, 0],
       [0, 1, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 1, 0],
       [2, 1, 1],
       [2, 2, 0],
       [2, 2, 1]], dtype=int64)

In [6]:
y = data.iloc[:,3].values

In [7]:
y

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
X_train

array([[2, 1, 1],
       [1, 2, 0],
       [1, 1, 0],
       [2, 2, 0],
       [2, 0, 0],
       [0, 2, 0],
       [2, 2, 1],
       [2, 0, 1],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 1],
       [2, 1, 0]], dtype=int64)

In [10]:
X_test

array([[1, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1]], dtype=int64)

In [11]:
y_train

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [12]:
y_test

array([0, 0, 0, 1], dtype=int64)

In [13]:
model = tree.DecisionTreeClassifier()

In [14]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [15]:
y_pred = model.predict(X_test)

In [16]:
df = pd.DataFrame(data=y_test, columns=['y_test'])
df['y_pred'] = y_pred

In [17]:
a = [1,1,0,]
b = np.array(a)
b = b.reshape(1, -1)
y_pred_single_obs = model.predict(b)
round(int(y_pred_single_obs), 2)

1

In [18]:
import joblib
joblib.dump(model, "employeesalaryprediction.pkl")

['employeesalaryprediction.pkl']