In [ ]:
#########################K-Cross Fold Validation #################################################

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

In [4]:
data = pd.read_csv('EmployeePerformanceset1.csv')

In [5]:
data.head()

MarriedID  MaritalStatusID  GenderID  EmpStatusID  DeptID  \
0          1                1         0            1       1   
1          0                2         1            1       1   
2          0                0         1            1       1   
3          1                1         0            1       1   
4          0                0         0            1       1   

   FromDiversityJobFairID  PayRate  Termd  PositionID  ManagerID  \
0                       1    28.50      0           1          1   
1                       0    23.00      0           1          1   
2                       0    29.00      0           1          1   
3                       0    21.50      1           2          1   
4                       0    16.56      0           2          1   

   EmpSatisfaction  SpecialProjectsCount  PerfScoreID  
0                2                     6            3  
1                4                     4            3  
2                5                     5            3  
3                3                     4            3  
4                3                     5            3

In [6]:
X = data.iloc[:,:-1].values

In [7]:
y = data.iloc[:,12].values

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
######### Using Logistic Regression################################
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.8225806451612904

In [10]:
############ Using Svm #############################

svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.8064516129032258

In [11]:
################## Random Forest ########################

rf = RandomForestClassifier(n_estimators=380)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8225806451612904

In [12]:
################## Using Decision Tree ########################
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X,y)

0.9483870967741935

In [13]:
################################################################################################################################################################
##################################### K Cross Validation For Evalluting Performances#################################################



In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
##############Logistic regression model performance using cross_val_score#####################

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X,y,cv=3)

array([0.40384615, 0.78640777, 0.75728155])

In [16]:
###############svm model performance using cross_val_score##################################

cross_val_score(SVC(gamma='auto'),X, y,cv=3)

array([0.77884615, 0.78640777, 0.78640777])

In [17]:
########################random forest performance using cross_val_score###########################

cross_val_score(RandomForestClassifier(n_estimators=40),X, y,cv=3)

array([0.76923077, 0.66019417, 0.78640777])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix()