In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

In [2]:
data = pd.read_csv('EmployeeArtitiondataset.csv')

In [3]:
data.head()

Age  BusinessTravel  DailyRate  Department  DistanceFromHome  Education  \
0   41               1       1102           1                 1          2   
1   49               2        279           2                 8          1   
2   37               1       1373           2                 2          2   
3   33               2       1392           2                 3          4   
4   27               1        591           2                 2          1   

   EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  \
0               1              1               1                        2   
1               1              1               2                        3   
2               2              1               4                        4   
3               1              1               5                        4   
4               3              1               7                        1   

   ...  StandardHours  StockOptionLevel  TotalWorkingYears  \
0  ...             80                 0                  8   
1  ...             80                 1                 10   
2  ...             80                 0                  7   
3  ...             80                 0                  8   
4  ...             80                 1                  6   

   TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                      0                1               6                   4   
1                      3                3              10                   7   
2                      3                3               0                   0   
3                      3                3               8                   7   
4                      3                3               2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager  Attrition  
0                        0                     5          1  
1                        1                     7          0  
2                        0                     0          1  
3                        3                     0          0  
4                        2                     2          0  

[5 rows x 35 columns]

In [4]:
X = data.iloc[:,:-1].values

In [5]:
X

array([[  41,    1, 1102, ...,    4,    0,    5],
       [  49,    2,  279, ...,    7,    1,    7],
       [  37,    1, 1373, ...,    0,    0,    0],
       ...,
       [  34,    3, 1065, ...,    5,    8,    7],
       [  37,    1,  408, ...,    0,    0,    0],
       [  46,    2, 1211, ...,    6,    0,    8]], dtype=int64)

In [7]:
y = data.iloc[:,34].values

In [8]:
y

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0], dtype=int64)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
X_train

array([[  29,    1,  153, ...,    5,    0,    8],
       [  44,    1, 1459, ...,    2,    1,    3],
       [  39,    1,  895, ...,    0,    0,    0],
       ...,
       [  41,    1, 1102, ...,    4,    0,    5],
       [  37,    1,  408, ...,    0,    0,    0],
       [  30,    2,  721, ...,    8,    3,    7]], dtype=int64)

In [11]:
X_test

array([[   46,     1,   705,     1,     2,     4,     4,     1,    38,
            2,     0,    83,     3,     5,     8,     1,     0, 18947,
        22822,     3,     1,     0,    12,     3,     4,    80,     0,
           22,     2,     2,     2,     2,     2,     1],
       [   27,     1,   591,     2,     2,     1,     3,     1,     7,
            1,     1,    40,     3,     1,     5,     2,     1,  3468,
        16632,     9,     1,     0,    12,     3,     4,    80,     1,
            6,     3,     3,     2,     2,     2,     2],
       [   32,     2,  1125,     2,    16,     1,     1,     1,    33,
            2,     0,    72,     1,     1,     4,     1,     0,  3919,
         4681,     1,     1,     1,    22,     4,     2,    80,     0,
           10,     5,     3,    10,     2,     6,     7],
       [   33,     1,   924,     2,     2,     3,     3,     1,    39,
            3,     1,    78,     3,     1,     3,     4,     0,  2496,
         6670,     4,     1,     0,    11,   

In [12]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [13]:
y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [14]:
model = tree.DecisionTreeClassifier()

In [15]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [16]:
y_pred = model.predict(X_test)

In [17]:
df = pd.DataFrame(data=y_test, columns=['y_test'])
df['y_pred'] = y_pred

In [18]:
a = [41,1,1103,1,1,2,1,1,1,2,0,94,3,2,1,4,0,5996,18500,7,1,1,11,3,1,80,0,8,0,1,6,4,0,5]
b = np.array(a)
b = b.reshape(1, -1)
y_pred_single_obs = model.predict(b)
round(int(y_pred_single_obs), 2)

1

In [22]:
import joblib
joblib.dump(model, "employeeattrmodel.pkl")

['employeeattrmodel.pkl']