In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

In [3]:
data = pd.read_csv('EmployeePerformanceset1.csv')


NameError: name 'pd' is not defined

In [2]:
X = data.iloc[:,:-1].values

NameError: name 'data' is not defined

In [4]:
X

array([[1., 1., 0., ..., 1., 2., 6.],
       [0., 2., 1., ..., 1., 4., 4.],
       [0., 0., 1., ..., 1., 5., 5.],
       ...,
       [1., 1., 1., ..., 7., 4., 5.],
       [0., 0., 1., ..., 7., 3., 4.],
       [0., 4., 0., ..., 7., 4., 8.]])

In [5]:
y = data.iloc[:,12].values

In [6]:
y

array([3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 4,
       3, 3, 1, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 3, 4, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 2, 4, 3, 3, 4, 3, 3, 3,
       3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 2, 4, 3, 3, 3, 2, 3, 3,
       4, 3, 3, 1, 1, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 2, 3, 4, 3,
       3, 3, 4, 3, 4, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 4, 4, 3, 3, 3, 2,
       3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 4, 3, 2,
       4, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 1, 4, 1, 3, 4, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 3,
       3, 3, 4, 3, 3, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 4, 3, 4, 3, 3, 3, 3,

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
X_train

array([[ 0.,  0.,  0., ..., 21.,  5.,  0.],
       [ 0.,  0.,  0., ..., 11.,  4.,  0.],
       [ 0.,  0.,  1., ..., 12.,  3.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 12.,  2.,  0.],
       [ 1.,  1.,  0., ...,  4.,  5.,  7.],
       [ 1.,  1.,  1., ..., 19.,  5.,  0.]])

In [9]:
X_test

array([[ 1.  ,  1.  ,  0.  ,  1.  ,  1.  ,  1.  , 34.95,  0.  , 26.  ,
         3.  ,  4.  ,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  5.  ,  0.  , 21.  ,  0.  , 19.  ,
        16.  ,  3.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  2.  ,  3.  ,  0.  , 61.3 ,  0.  , 27.  ,
         4.  ,  5.  ,  6.  ],
       [ 1.  ,  1.  ,  0.  ,  5.  ,  5.  ,  1.  , 15.  ,  1.  , 19.  ,
        39.  ,  5.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  3.  ,  0.  , 31.4 ,  0.  ,  9.  ,
         4.  ,  3.  ,  5.  ],
       [ 1.  ,  1.  ,  0.  ,  5.  ,  5.  ,  0.  , 25.  ,  1.  , 20.  ,
        39.  ,  3.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  1.  ,  6.  ,  0.  , 55.  ,  0.  ,  3.  ,
        21.  ,  3.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  5.  ,  0.  , 17.  ,  0.  , 19.  ,
        19.  ,  4.  ,  0.  ],
       [ 0.  ,  2.  ,  0.  ,  1.  ,  5.  ,  0.  , 14.  ,  0.  , 19.  ,
        20.  ,  4.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  5.  ,  0.  , 26.1 ,  0.  , 20.  ,
        16.  ,  4.  

In [10]:
y_train

array([4, 3, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 4, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 4, 3, 4, 4,
       1, 3, 3, 1, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 3, 3,
       3, 4, 3, 3, 3, 1, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2,
       3, 2, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 4, 1, 3, 3, 3, 3,
       3, 3, 4, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 2, 3, 1, 3, 3, 3, 3, 4, 2, 3, 3, 4, 4, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 4, 1, 4, 3], dtype=int64)

In [11]:
y_test

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 2, 4, 3, 3,
       3, 3, 3, 1, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 2, 3], dtype=int64)

In [12]:
model = tree.DecisionTreeClassifier()

In [13]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [14]:
y_pred = model.predict(X_test)

In [15]:
df = pd.DataFrame(data=y_test, columns=['y_test'])
df['y_pred'] = y_pred

In [17]:
a = [1,1,0,1,1,1,34.95,0,26,3,0,7]
b = np.array(a)
b = b.reshape(1, -1)
y_pred_single_obs = model.predict(b)
round(int(y_pred_single_obs), 2)

2

In [19]:
import joblib
joblib.dump(model, "employeeperformscore.pkl")

['employeeperformscore.pkl']