In [1]:
#########################K-Cross Fold Validation #################################################

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

In [4]:
data = pd.read_csv('salaries1.csv')

In [5]:
data.head()

company  job  degree  salary_more_then_100k
0        1    0       0                      0
1        1    0       1                      0
2        1    1       0                      1
3        1    1       1                      1
4        1    2       0                      0

In [6]:
X = data.iloc[:,:-1].values

In [7]:
y = data.iloc[:,3].values

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
######### Using Logistic Regression################################
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.5

In [11]:
############ Using Svm #############################

svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.25

In [12]:
################## Random Forest ########################

rf = RandomForestClassifier(n_estimators=380)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.25

In [13]:
################## Using Decision Tree ########################
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X,y)

0.8125

In [ ]:
################################################################################################################################################################
##################################### K Cross Validation For Evalluting Performances#################################################



In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
##############Logistic regression model performance using cross_val_score#####################

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X,y,cv=3)

array([0.33333333, 0.8       , 0.6       ])

In [16]:
###############svm model performance using cross_val_score##################################

cross_val_score(SVC(gamma='auto'),X, y,cv=3)

array([0.16666667, 0.6       , 0.6       ])

In [17]:
########################random forest performance using cross_val_score###########################

cross_val_score(RandomForestClassifier(n_estimators=40),X, y,cv=3)

array([0.33333333, 0.6       , 0.8       ])